#' Plotting a skyline model.
#'
#' @param data data.frame; data.frame generated by prepare_sky* function.
#' @param y_log logical; if TRUE, y axis is in log10 space.
#' @param alpha numeric; opacity of ribbon
#' @param color character string; color for line.
#' @param fill character string; color for ribbons.
#' @param color_by character string; name of column for coloring the line.
#' @param fill_by character string; name of column for filling the ribbon.
#' @param group_by character string; name of column for grouping in facet.
#' @param facet_args list; named list of arguments (other than `facets`) passed
#'   to [ggplot2::facet_wrap()]. Sub-plots are superimposed if NULL and group_by
#'   is specified.
#' @returns ggplot2 object.
#' @import ggplot2 scales
#' @importFrom rlang .data
#' @export
skyplot <-
  function(data,
           y_log = T,
           alpha = 0.5,
           color = NULL,
           fill = NULL,
           color_by = NULL,
           fill_by = NULL,
           group_by = NULL,
           facet_args = list()) {
    by_analysis <- !is.null(color)

    aes_line <- aes(
      x = .data$time,
      y = .data$pop_size
    )

    aes_ribbon <- aes(
      ymin = .data$pop_size_low,
      ymax = .data$pop_size_high
    )

    if (!is.null(color_by)) {
      aes_line$color <- substitute(.data[[color_by]])
    }
    if (!is.null(fill_by)) {
      aes_ribbon$fill <- substitute(.data[[fill_by]])
    }

    graph <- ggplot(data, aes_line) +
      theme_bw() +
      theme(
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.border = element_rect(colour = "black"),
        legend.title = element_blank()
      )

    if (!is.null(color)) {
      graph <- graph + geom_line(color = color)
    } else {
      graph <- graph + geom_line()
    }

    if (!is.null(fill)) {
      graph <- graph + geom_ribbon(aes_ribbon, fill = fill, alpha = alpha)
    } else {
      graph <- graph + geom_ribbon(aes_ribbon, alpha = alpha)
    }

    if (y_log) {
      graph <- graph + scale_y_log10(
        breaks = trans_breaks("log10", function(x) {
          10^x
        }),
        labels = trans_format("log10", math_format(10^.x))
      )
    }
    if (!is.null(facet_args) & !is.null(group_by)) {
      facet_args[["facets"]] <- vars(.data[[group_by]])
      graph <- graph + do.call("facet_wrap", facet_args)
    }

    graph + xlab("Time") + ylab("Effective population size")
  }
